# theme: minima
title: Bling
# url: https://docs.bling.dev/
include_custom_head: true
exclude:
  - .git
author:
  - name: Vishal Apte
  - email: vishal@enine.dev
social:
  - linkedin: https://www.linkedin.com/showcase/bling-store/
